Repository All-In-Job/frontend, pull requests merged in 2023-10, with the labels that each got.

#45 feat: 가입계정 찾기 validate 추가
  src/components/Aside/Aside.styles.ts
  src/components/Aside/Aside.tsx
  src/components/CardList/PassionTempList/PassionTempList.style.ts
  src/components/CardList/PassionTempList/PassionTempList.tsx
  src/components/Navigation/MyInfoNav/MyInfoNav.tsx
  src/components/Navigation/MyInfoNav/myInfoNav.styles.ts
  src/components/PassionTempList/PassionTempList.tsx
  src/pages/findID/FindID.tsx
  src/pages/findID/findID.styles.ts
  src/pages/login/Login.tsx
  src/pages/login/login.styles.ts
  src/pages/login/res/img/google.png
  src/pages/login/res/img/kakao.png
  src/routers/router.tsx
  yarn.lock
Labels: feature

#47 Competition search by keyword
  src/components/Badge/BadgeHeader.tsx
  src/components/Badge/MultiSelectHashTagListForIndicator/index.tsx
  src/components/Badge/MultiSelectHashTagListForIndicator/res/images/close.svg
  src/components/Badge/MultiSelectHashTagListForSelect/index.tsx
  src/components/Badge/badge.style.ts
  src/components/Badge/index.tsx
  src/components/Badge/mock/hashTags.ts
  src/components/Badge/res/image/refresh.svg
  src/components/Badge/type.ts
  src/components/HashTag/index.tsx
Labels: chore, feature

#53 Profile design system apply
  src/pages/home/AsideProfile/Profile.tsx
  src/pages/home/AsideProfile/Temperature.tsx
  src/pages/home/AsideProfile/UserTabs.tsx
  src/pages/home/AsideProfile/asideProfile.style.ts
Labels: chore

#55 chore:열정온도 컴포넌트 깨짐 현상을 html-ul,li 태그에서 svg g mask rect 태그로 변경하여 해결
  src/components/PassionThermometer/BarPiece.tsx
  src/components/PassionThermometer/Thermometer.tsx
  src/components/PassionThermometer/res/img/temprature.svg
  src/pages/home/AsideProfile/Solution.tsx
  src/pages/home/AsideProfile/SolutionItem.tsx
  src/pages/home/AsideProfile/mock/solution.ts
  src/pages/home/PassionTemperature/Indicator.tsx
  src/pages/home/PassionTemperature/TemperatureCategory.tsx
  src/pages/home/PassionTemperature/Thermometer/Indicator.tsx
  src/pages/home/PassionTemperature/Thermometer/constants.ts
  src/pages/home/PassionTemperature/Thermometer/index.tsx
  src/pages/home/PassionTemperature/Thermometer/mock/index.ts
  src/pages/home/PassionTemperature/Thermometer/types.ts
  src/pages/home/PassionTemperature/Thermometer/utils.ts
  src/pages/home/PassionTemperature/constants.ts
  src/pages/home/PassionTemperature/index.tsx
  src/pages/home/PassionTemperature/mock/categories.ts
  src/pages/home/PassionTemperature/utils.ts
Labels: chore

#58 chore:카테고리 필터 컴포넌트 추가
  src/components/CategoryFilter/CategoryFilterHeader.tsx
  src/components/CategoryFilter/categoryFilter.style.ts
  src/components/CategoryFilter/index.tsx
  src/components/CategoryFilter/mock/categories.ts
  src/components/CategoryFilter/type.ts
  src/components/HashTag/index.tsx
  src/components/HashTagFilter/BadgeHeader.tsx
  src/components/HashTagFilter/MultiSelectIndicator/index.tsx
  src/components/HashTagFilter/MultiSelectIndicator/res/images/close.svg
  src/components/HashTagFilter/badge.style.ts
  src/components/HashTagFilter/index.tsx
  src/components/HashTagFilter/mock/hashTags.ts
  src/components/HashTagFilter/res/image/refresh.svg
  src/components/HashTagFilter/type.ts
  src/components/HashTagList/index.tsx
Labels: chore
